training:
  seed: 0
  resume_from_checkpoint: null  # null to start from scratch
  inference_mode: gradient_ascent  # mean, all, random_search, gradient_ascent
  inference_kwargs:
    num_steps: 1
    lr: 0.1
    optimizer: adam
    optimizer_kwargs:
      b2: 0.9
  batch_size: 128  # this has to be divisible by gradient_accumulation_steps * num_devices
  gradient_accumulation_steps: 2  # the higher the slower but the lower memory usage while keeping effective batch size constant
  total_num_steps: 1000000
  log_every_n_steps: 100  # this has to respect dataset_size >= batch_size * log_every_n_steps
  eval_every_n_logs: 50  # null to disable eval
  save_checkpoint_every_n_logs: 50  # null to disable checkpointing
  learning_rate: 4e-4
  prior_kl_coeff: 1e-4
  pairwise_kl_coeff: null
  mixed_precision: False  # if True, it uses bfloat16 for activations (params stay in float32)
  online_data_augmentation: True
  task_generator:
    num_workers: 64
    num_pairs: 4
    class: ARC
  train_datasets:

wandb:
  project: ARC-LPN
  name: full-arc-ga

eval:
  eval_datasets:
  test_datasets:
    - generator: ARC
      task_generator_kwargs:
      name: mean
      num_pairs: 4
      length: 64
      batch_size: 64 # Note: batch_size=16 fails on H100 for some strange reason
      num_tasks_to_show: 64
    - generator: ARC
      task_generator_kwargs:
      name: gradient_ascent_20
      num_pairs: 4
      length: 64
      batch_size: 64
      num_tasks_to_show: 64
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 20
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - generator: ARC
      task_generator_kwargs:
      name: gradient_ascent_100
      num_pairs: 4
      length: 64
      batch_size: 64
      num_tasks_to_show: 64
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 100
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
  json_datasets:
    - challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      name: mean
      only_n_tasks: 100
      num_tasks_to_show: 50
    - challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      name: gradient_ascent_20
      only_n_tasks: 100
      num_tasks_to_show: 50
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 20
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      name: gradient_ascent_100
      only_n_tasks: 100
      num_tasks_to_show: 50
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 100
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - challenges: json/arc-agi_evaluation_challenges.json
      solutions: json/arc-agi_evaluation_solutions.json
      name: mean
      only_n_tasks: 100
      num_tasks_to_show: 50
    - challenges: json/arc-agi_evaluation_challenges.json
      solutions: json/arc-agi_evaluation_solutions.json
      name: gradient_ascent_20
      only_n_tasks: 100
      num_tasks_to_show: 50
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 20
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - challenges: json/arc-agi_evaluation_challenges.json
      solutions: json/arc-agi_evaluation_solutions.json
      name: gradient_ascent_100
      only_n_tasks: 100
      num_tasks_to_show: 50
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 100
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9

encoder_transformer:
  _target_: src.models.utils.EncoderTransformerConfig
  max_rows: 30
  max_cols: 30
  num_layers: 4
  transformer_layer:
    _target_: src.models.utils.TransformerLayerConfig
    num_heads: 8
    emb_dim_per_head: 32
    mlp_dim_factor: 4.0
    dropout_rate: 0.0
    attention_dropout_rate: 0.0
  latent_dim: 256
  variational: True
  latent_projection_bias: False


decoder_transformer:
  _target_: src.models.utils.DecoderTransformerConfig
  max_rows: 30
  max_cols: 30
  num_layers: 8
  transformer_layer:
    _target_: src.models.utils.TransformerLayerConfig
    num_heads: 8
    emb_dim_per_head: 32
    mlp_dim_factor: 4.0
    dropout_rate: 0.0
    attention_dropout_rate: 0.0
