# Run with: python src/train.py --config-path configs/arc_train_overfit --config-name overfit-general training.task_generator.overfit_task=<task_id>

training:
  seed: 0
  resume_from_checkpoint: null  # null to start from scratch
  inference_mode: mean  # mean, all, random_search, gradient_ascent
  batch_size: 128  # this has to be divisible by gradient_accumulation_steps * num_devices
  gradient_accumulation_steps: 4  # the higher the slower but the lower memory usage while keeping effective batch size constant
  total_num_steps: 10000
  log_every_n_steps: 20  # this has to respect dataset_size >= batch_size * log_every_n_steps
  eval_every_n_logs: 25  # null to disable eval
  save_checkpoint_every_n_logs: null  # null to disable checkpointing
  learning_rate: 4e-4
  prior_kl_coeff: 1e-4
  pairwise_kl_coeff: null
  mixed_precision: False  # if True, it uses bfloat16 for activations (params stay in float32)
  online_data_augmentation: False
  task_generator:
    num_workers: 48
    num_pairs: 4
    class: ARC
    overfit_task: null # Specify via command line
  train_datasets:

wandb:
  project: ARC-LPN-MegaOverfit
  name: task-${training.task_generator.overfit_task}

eval:
  eval_datasets:
  test_datasets:
    - generator: ARC
      task_generator_kwargs:
        overfit_task: ${training.task_generator.overfit_task}
      name: arc_overfit_mean
      num_pairs: 4
      length: 128
      batch_size: 16
      num_tasks_to_show: 48
    - generator: ARC
      task_generator_kwargs:
      name: generator_gradient_ascent_1
      num_pairs: 4
      length: 48
      batch_size: 16
      num_tasks_to_show: 48
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 1
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - generator: ARC
      task_generator_kwargs:
      name: generator_gradient_ascent_20
      num_pairs: 4
      length: 48
      batch_size: 16
      num_tasks_to_show: 48
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 20
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - generator: ARC
      task_generator_kwargs:
      name: generator_gradient_ascent_100
      num_pairs: 4
      length: 48
      batch_size: 16
      num_tasks_to_show: 48
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 100
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - generator: ARC
      task_generator_kwargs:
      name: generator_gradient_ascent_500
      num_pairs: 4
      length: 48
      batch_size: 16
      num_tasks_to_show: 48
      inference_mode: gradient_ascent
      inference_kwargs:
        num_steps: 500
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
  json_datasets:
    - name: json_mean
      challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      overfit_task: ${training.task_generator.overfit_task}
      inference_mode: mean
      num_tasks_to_show: 1
    - name: json_gradient_ascent_1
      challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      overfit_task: ${training.task_generator.overfit_task}
      inference_mode: gradient_ascent
      num_tasks_to_show: 1
      inference_kwargs:
        num_steps: 1
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - name: json_gradient_ascent_10
      challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      overfit_task: ${training.task_generator.overfit_task}
      inference_mode: gradient_ascent
      num_tasks_to_show: 1
      inference_kwargs:
        num_steps: 10
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9
    - name: json_gradient_ascent_100
      challenges: json/arc-agi_training_challenges.json
      solutions: json/arc-agi_training_solutions.json
      overfit_task: ${training.task_generator.overfit_task}
      inference_mode: gradient_ascent
      num_tasks_to_show: 1
      inference_kwargs:
        num_steps: 100
        lr: 0.1
        optimizer: adam
        optimizer_kwargs:
          b2: 0.9

encoder_transformer:
  _target_: src.models.utils.EncoderTransformerConfig
  max_rows: 30
  max_cols: 30
  num_layers: 0
  transformer_layer:
    _target_: src.models.utils.TransformerLayerConfig
    num_heads: 6
    emb_dim_per_head: 16
    mlp_dim_factor: 1.0
    dropout_rate: 0.0
    attention_dropout_rate: 0.0
  latent_dim: 32
  variational: True
  latent_projection_bias: False


decoder_transformer:
  _target_: src.models.utils.DecoderTransformerConfig
  max_rows: 30
  max_cols: 30
  num_layers: 4
  transformer_layer:
    _target_: src.models.utils.TransformerLayerConfig
    num_heads: 8
    emb_dim_per_head: 32
    mlp_dim_factor: 2.0
    dropout_rate: 0.0
    attention_dropout_rate: 0.0
